services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - 50
        calls:
            - [ setLocale, [%locale%] ]

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_platform.antispam"
        tags:
          - { name: twig.extension }

    oc_platform.email.application_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.application_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    oc_platform.purger.advert:
        class: OC\PlatformBundle\Purge\Purge
        arguments:
            - "@doctrine.orm.entity_manager"

    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        argurments:
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
#        tags:
#            - { name: validator.constraint_validator, alias: oc_platform_antiflood }

    oc_platform.form.ckeditor:
        class: OC\PlatformBundle\Form\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor }

    oc_platformbundle.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platformbundle.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_platformbundle.beta.html_adder"
            - "2018-06-01"
        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: processBeta, priority: 2 }
            - { name: kernel.event_listener, event: kernel.controller, method: ignoreBeta }

    oc_platform.bigbrother.message_notificator:
        class: OC\PlatformBundle\Bigbrother\MessageNotificator
        arguments:
            - "@mailer"

    oc_platform.bigbrother.message_listener:
        class: OC\PlatformBundle\Bigbrother\MessageListener
        arguments:
            - "@oc_platform.bigbrother.message_notificator"
            - ["Alexandre", "Marie", "Piere", "ivano",]
        tags:
            - { name : kernel.event_subscriber }

    oc_platform.paramconverter.json:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
           - { name : request.param_converter }