<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApplcationsWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('app');
        $qb->leftJoin('app.advert', 'a')
            ->addSelect('a')
            ->orderBy('date', 'desc')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    public function isFlood($ip, $times)
    {

    }

}
